### ISSUE TITLE
请问这个sdk可以用在小程序中吗？

### ISSUE THREAD

**Issue by Powerfan** [breakstring/xunfeisdk#1]
我是技术小白，翻遍整个网络终于找到了一个webapi的详细说明文档，请问这个sdk能直接用在微信小程序中吗？谢谢！

**Comment by breakstring** [comment]
不能直接用于微信小程序的客户端脚本里。
1. 讯飞WebAPI必须要设定IP地址白名单才能用
2. 我只在NodeJS的环境下测试过，不太确定是否所有API在微信小程序的脚本中可用。

所以，要在微信小程序中使用的话，如果你的微信小程序的服务端使用NodeJS的话，我觉得问题不大。也就是微信端把数据发送到你的服务端，服务端再转发到讯飞的服务器来请求。而不是直接从微信小程序的脚本中直接请求讯飞的服务器。

**Comment by Powerfan** [comment]
@breakstring 谢谢谢谢！

按照讯飞的文档忙活了一晚上部署在小程序（无服务端）里，才发现讯飞WebAPI是不支持在客户端使用的
