### ISSUE TITLE
讯飞语音合成返回文件是空的

### ISSUE THREAD

**Issue by winssps** [breakstring/xunfeisdk#4]
![image](https://user-images.githubusercontent.com/16569664/42124617-a8864d66-7c98-11e8-91bc-65ddc833dc34.png)
我是用这里的APIkey 
![image](https://user-images.githubusercontent.com/16569664/42124620-c26db2aa-7c98-11e8-9f0a-67a3549f9b6a.png)

**Comment by breakstring** [comment]
返回信息是啥？
IP白名单加了么？

**Comment by winssps** [comment]
那应该是IP白名单的问题。我不是在云服务器运行的，是在Mac上运行的程序，是加什么IP呢？

**Comment by winssps** [comment]
嗯我加了IP白名单就可以了，谢谢您

**Comment by breakstring** [comment]
客气。
