### ISSUE TITLE
语音听写出错

### ISSUE THREAD

**Issue by WuHuaJi0** [breakstring/xunfeisdk#5]
没有报错，但是反复测试了几个文件，识别出来的文字，和语音完全对不上。
不知道哪里不对了。返回结果：
```
{ code: '0',
  data: '咋啦啊。',
  desc: 'success',
  sid: 'zat0003855f@ch6b010ece31003d3700' }
```

但实际上我的语音说的是：讯飞语音

**Comment by breakstring** [comment]
讯飞对于音频的码率、格式之类的要求比较严格，否则的话的确会出现识别不出来的情况。你用什么音频处理软件对比一下我的test文件夹中的测试音频和你的音频的格式之类的看看？

**Comment by WuHuaJi0** [comment]
确实，对比了你的测试文件，识别是没问题的，我再看看我的文件哪里不对了。
多谢 ：）

**Comment by breakstring** [comment]
客气

**Comment by WuHuaJi0** [comment]
是采样率的问题，之前没太明白采样率啥意思，现在明白了 ：）
