### ISSUE TITLE
有关比特率问题

### ISSUE THREAD

**Issue by Tomotoes** [breakstring/xunfeisdk#6]
我在前端采集之后的语音 比特率都是705, 讯飞,百度识别都失败.
我看您 测试音频的比特率都是 256,很好奇,您是怎么采集的呢?

我在网上搜了很久,也没找到对应 频率互换的方法..

**Comment by breakstring** [comment]
呃。。。我忘了我怎么采集的了，不过。。。我的测试程序并没有从前端页面上直接采集，当时可能是用啥桌面软件采集的吧。不过你说你的比特率705？这个。。。我怎么觉得这个数值有些怪呢？会不会录音有问题？。。。。
好吧，还有，其实也有不少JS的库可以用来转换音频的比特率的，例如 https://github.com/zhuker/lamejs （我没试验，只是随手替你搜了下，你可以试试看）

**Comment by Tomotoes** [comment]
其实在提问之后,我已经找到比特率转换的解决方案了,利用fluent-ffmpeg,不过还是识别有误...
总之,非常感谢 您的解答!
